site_name: Saffy
theme:
  name: 'readthedocs'
extra_css: [extra.css]
site_favicon: favicon.ico
repo_url: https://github.com/saffy-team/saffy
nav:
  - Home: 'index.md'
  - Tutorials:
    - Basics: 'Tutorials/Basics.md'
    - Custom Generators: 'Tutorials/custom_generators.md'
  - SignalManager: 'SignalManager.md'
  - Plugins:
      - PluginManager: 'Plugins/PluginManager.md'
      - Fourier: 'Plugins/Fourier.md'
      - Hilbert: 'Plugins/Hilbert.md'
      - Welch: 'Plugins/Welch.md'
      - Filters: 'Plugins/Filters.md'
      - Graphics: 'Plugins/Graphics.md'
      - Create Custom Plugins: 'Plugins/Create Custom Plugins.md'
  - FAQ: 'faq.md'
